# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssuntoSaberMais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45, verbose_name='assunto')),
                ('ordem', models.IntegerField(default=99, verbose_name='ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='disponível')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'assunto saber mais',
                'ordering': ('ordem',),
                'verbose_name_plural': 'assuntos saber mais',
            },
        ),
        migrations.CreateModel(
            name='UsuarioGuia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45, verbose_name='nome')),
                ('email', models.EmailField(max_length=45, verbose_name='e-mail')),
                ('cidade', models.CharField(max_length=45, verbose_name='cidade')),
                ('ja_fez_compras', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='já fez compras no Paraguai?')),
                ('quais_assuntos', models.CharField(blank=True, max_length=250, null=True, verbose_name='quais assuntos?')),
                ('ativo', models.BooleanField(default=True, verbose_name='disponível')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('assuntos', models.ManyToManyField(blank=True, to='core.AssuntoSaberMais')),
            ],
            options={
                'verbose_name': 'usuário guia',
                'ordering': ('-id',),
                'verbose_name_plural': 'usuários guia',
            },
        ),
    ]
